### ISSUE TITLE
“File /nix/store/.../bin/ocamlc, which package ocaml-system.5.1.1 depends upon, is no longer in your path”

### ISSUE THREAD

**Issue by OlivierNicole** [Julow/nix-opam-switch#2]
Installing a 5.1 switch and then trying to use it, opam complains that the Nix path no longer exists:
```
$ nix-opam-switch create 5.1
$ cd <some project>
$ opam install . --verbose --deps-only
[WARNING] Failed checks on guerre_webapp package definition from source at
          git+file:///home/olivier/hacking_days/2024_01_guerre_sur_le_web/guerre_webapp#main:
    error 23: Missing field 'maintainer'
  warning 25: Missing field 'authors'
  warning 35: Missing field 'homepage'
  warning 36: Missing field 'bug-reports'
  warning 68: Missing field 'license'
[WARNING] File /nix/store/w4zxwfn57qjvv0mi8v0si7bbv1lhdvca-ocaml-5.1.1/bin/ocamlc, which
          package ocaml-system.5.1.1 depends upon, is no longer in your PATH.
[ERROR] Package conflict!
  * Missing dependency:
    - ocaml-system.5.1.1: no longer available

No solution found, exiting
```

**Comment by Julow** [comment]
I think this is due to a missing `eval $(opam env)` before `opam install`. `ocamlc` and the other tools are installed in the new switch's bin directory, which should be in PATH after a environment refresh.

**Comment by OlivierNicole** [comment]
No, the issue persists even with an `eval $(opam env)`.

**Comment by OlivierNicole** [comment]
Strangely, the file is in the PATH from the normal shell:

```
$ eval $(opam env)

$ opam pin add dune.3.13 https://github.com/ocaml-wasm/dune.git
[NOTE] Package dune is already pinned to git+https://github.com/ocaml-wasm/dune.git (version 3.13).
[dune.3.13] synchronised (no changes)
dune is now pinned to git+https://github.com/ocaml-wasm/dune.git (version 3.13)

[WARNING] File /nix/store/w4zxwfn57qjvv0mi8v0si7bbv1lhdvca-ocaml-5.1.1/bin/ocamlc, which package ocaml-system.5.1.1 depends
          upon, is no longer in your PATH.
[ERROR] Package conflict!
  * Missing dependency:
    - ocaml-system.5.1.1: no longer available

[NOTE] Pinning command successful, but your installed packages may be out of sync.

$ which ocamlc
/home/olivier/woo/wasm_of_ocaml/_opam/bin/ocamlc

$ which ocamlc.opt
/home/olivier/woo/wasm_of_ocaml/_opam/bin/ocamlc.opt

$ file $(which ocamlc.opt)
/home/olivier/woo/wasm_of_ocaml/_opam/bin/ocamlc.opt: symbolic link to /nix/store/w4zxwfn57qjvv0mi8v0si7bbv1lhdvca-ocaml-5.1.1/bin/ocamlc.opt

$ file /nix/store/w4zxwfn57qjvv0mi8v0si7bbv1lhdvca-ocaml-5.1.1/bin/ocamlc.opt
/nix/store/w4zxwfn57qjvv0mi8v0si7bbv1lhdvca-ocaml-5.1.1/bin/ocamlc.opt: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/9y8pmvk8gdwwznmkzxa6pwyah52xy3nk-glibc-2.38-27/lib/ld-linux-x86-64.so.2, for GNU/Linux 3.10.0, not stripped

$ file /nix/store/w4zxwfn57qjvv0mi8v0si7bbv1lhdvca-ocaml-5.1.1/bin/ocamlc    
/nix/store/w4zxwfn57qjvv0mi8v0si7bbv1lhdvca-ocaml-5.1.1/bin/ocamlc: symbolic link to ocamlc.opt
```

**Comment by Julow** [comment]
Opam compares paths. Maybe it's dereferencing symlinks differently on some systems, making the comparisons fail ?
Can you try this branch ? https://github.com/Julow/nix-opam-switch/tree/ocamlc-no-longer-available

**Comment by OlivierNicole** [comment]
Thanks! Opam is still printing this warning at every command invocation:

```
[WARNING] File /nix/store/w4zxwfn57qjvv0mi8v0si7bbv1lhdvca-ocaml-5.1.1/bin/ocamlc, which package ocaml-system.5.1.1 depends upon, is no longer in your PATH.
```

but apart from that those commands work.

**Comment by Julow** [comment]
Thanks for trying! The fix is merged.

**Comment by OlivierNicole** [comment]
It still does not work reliably, sorry. Some commands will work, and all of a sudden nothing can be installed anymore.

```
$ opam install menhir
[WARNING] File /nix/store/qki86vwapkmmb3bdip6x868y3fdw9bsa-ocaml-4.14.2/bin/ocamlc, which package ocaml-system.4.14.2 depends upon, is no longer in your PATH.
[ERROR] Package conflict!
  * Missing dependency:
    - ocaml-system.4.14.2: no longer available

No solution found, exiting
```

**Comment by Julow** [comment]
Aren't you using a switch created using an older version of the tool ?

**Comment by OlivierNicole** [comment]
No, I just tried reinstalling the latest revision on main.

**Comment by Julow** [comment]
I fail to reproduce the problem on switches that have survived numerous nix gc and nixpkgs upgrades.
Does this happen reproducibly ?

**Comment by OlivierNicole** [comment]
I’m not sure how to reproduce it. You don’t seem to experience it even though we both use NixOS.
